### ISSUE TITLE
default install and run on ubuntu system presents "FAIL"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [stressapptest/stressapptest#1]
```
What steps will reproduce the problem?
1. Provision a new ubuntu server
2. apt-get update
3. install stressaptest
4. run stressapptest

What is the expected output? What do you see instead?

I expected performance benchmarks.  Instead I saw the following:

alan@dev1:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 9.04
Release:        9.04
Codename:       jaunty
alan@dev1:~$ stressapptest
Log: Commandline - stressapptest
Stats: SAT revision 1.0.0_autoconf, 64 bit binary
Log: root @ dev1 on Thu Oct 15 17:52:53 PDT 2009 from open source release
Log: 1 nodes, 8 cpus.
Log: Defaulting to 8 copy threads
Log: Total 7894 MB. Free 7441 MB. Hugepages 0 MB. Targeting 7308 MB (92%)
Process Error: Unsupported system, no error reporting available
Log: Command line option '-A' bypasses this error.
Process Error: Sat::Initialize() failed

Status: FAIL - test encountered procedural errors

Process Error: Fatal issue encountered. See above logs for details.
alan@dev1:~$ uname -a
Linux dev1 2.6.28-15-generic #52-Ubuntu SMP Wed Sep 9 10:48:52 UTC 2009
x86_64 GNU/Linux
alan@dev1:~$


What version of the product are you using? On what operating system?

I am using version " revision 1.0.0_autoconf, 64 bit binary" on an Ubuntu
LInux OS.

Please provide any additional information below.

Pretty straightforward.  I installed g++, did ./configure, make, make
install, then run and got the FAIL error.
```

Original issue reported on code.google.com by `alanhan...@gmail.com` on 16 Oct 2009 at 12:58

**Comment by opnbloch** [comment]
~$ stressapptest -W
Log: Commandline - stressapptest -W
Stats: SAT revision 1.0.6_autoconf, 64 bit binary
Log: buildd @ lgw01-amd64-022 on Thu Apr  5 10:28:35 UTC 2018 from open source release
Log: 1 nodes, 16 cpus.
Log: Defaulting to 16 copy threads
Log: Total 32175 MB. Free 27094 MB. Hugepages 0 MB. Targeting 30375 MB (94%)
Log: Prefer plain malloc memory allocation.
Process Error: memalign returned 0
Process Error: failed to allocate memory
Process Error: Sat::Initialize() failed
Status: FAIL - test encountered procedural errors
Process Error: Fatal issue encountered. See above logs for details.





~$ stressapptest -A
Log: Commandline - stressapptest -A
Stats: SAT revision 1.0.6_autoconf, 64 bit binary
Log: buildd @ lgw01-amd64-022 on Thu Apr  5 10:28:35 UTC 2018 from open source release
Log: 1 nodes, 16 cpus.
Log: Defaulting to 16 copy threads
Log: Total 32175 MB. Free 27094 MB. Hugepages 0 MB. Targeting 30375 MB (94%)
Log: Prefer plain malloc memory allocation.
Process Error: memalign returned 0
Process Error: failed to allocate memory
Process Error: Sat::Initialize() failed
Status: FAIL - test encountered procedural errors
Process Error: Fatal issue encountered. See above logs for details.





~$ stressapptest
Log: Commandline - stressapptest
Stats: SAT revision 1.0.6_autoconf, 64 bit binary
Log: buildd @ lgw01-amd64-022 on Thu Apr  5 10:28:35 UTC 2018 from open source release
Log: 1 nodes, 16 cpus.
Log: Defaulting to 16 copy threads
Log: Total 32175 MB. Free 27093 MB. Hugepages 0 MB. Targeting 30375 MB (94%)
Log: Prefer plain malloc memory allocation.
Process Error: memalign returned 0
Process Error: failed to allocate memory
Process Error: Sat::Initialize() failed
Status: FAIL - test encountered procedural errors
Process Error: Fatal issue encountered. See above logs for details.
aitron@octane:~$

**Comment by nickjsanders** [comment]
It looks like you have already allocated a lot of memory for running other
things, so the default region of memory for testing can't be allocated. You
can use "-M 25000" to test a lesser portion of memory or close some other
programs to get more free memory.
