### ISSUE TITLE
Whether the aarch64 architecture can be cross-compiled

### ISSUE THREAD

**Issue by yumdeer** [stressapptest/stressapptest#102]

**Comment by yumdeer** [comment]
![image](https://user-images.githubusercontent.com/41462565/210322278-372416c0-3a2f-4615-b08a-27ccbc8e305f.png)

**Comment by yumdeer** [comment]
![image](https://github.com/stressapptest/stressapptest/assets/41462565/f91d8cbd-81e7-4226-ada5-197ac022f143)

**Comment by sebhz** [comment]
For a static build:

`./configure --host=aarch64-linux-gnu CXX=/usr/bin/aarch64-linux-gnu-g++-9 LDFLAGS=-static`

Your CXX definition may vary depending on your distro and the toolchain you are using.
