### ISSUE TITLE
make fail under debian OS(5.4.210.bsk.business.3-amd64)

### ISSUE THREAD

**Issue by qhbqyj** [stressapptest/stressapptest#103]
make  all-am
make[2]: Entering directory '/root/stressapptest/src'
g++ -DHAVE_CONFIG_H -I.     -DCHECKOPTS -Wreturn-type -Wunused -Wuninitialized -Wall -O3 -funroll-all-loops  -funroll-loops -DNDEBUG -MT main.o -MD -MP -MF .deps/main.Tpo -c -o main.o main.cc
In file included from finelock_queue.h:29,
                 from sat.h:28,
                 from main.cc:18:
os.h: In static member function ‘static uint64 OsLayer::GetTimestamp()’:
os.h:282:11: error: ‘__rdtsc’ was not declared in this scope
     tsc = __rdtsc();
           ^~~~~~~
os.h:282:11: note: suggested alternative: ‘__dt ’
     tsc = __rdtsc();
           ^~~~~~~
           __dt 
make[2]: *** [Makefile:326: main.o] Error 1
make[2]: Leaving directory '/root/stressapptest/src'
make[1]: *** [Makefile:192: all] Error 2
make[1]: Leaving directory '/root/stressapptest/src'
make: *** [Makefile:312: all-recursive] Error 1

**Comment by sebhz** [comment]
Hi !

Please check the workaround mentioned in https://github.com/stressapptest/stressapptest/issues/98. It will probably fix your issue. I'll make a PR to have it merged in the main branch if Nick would agree.

Seb
