### ISSUE TITLE
Is it possible to know how why have 20 seconds delay between issuing the stressapptest command and system running

### ISSUE THREAD

**Issue by AlecHsiao** [stressapptest/stressapptest#107]
We run the command to enable the StressAppTest with testing time, take our 100 seconds test for example, after issuing the command it is 04/13 21:02:32, but it start from 21:02:51 so it takes around 20 seconds before running, is it possible to know why we have the 20 seconds before running? 

2023/04/13-21:02:32(CST) Log: Prefer plain malloc memory allocation.
2023/04/13-21:02:32(CST) Log: Using mmap() allocation at 0x7f0e4b600000.
2023/04/13-21:02:32(CST) Stats: Starting SAT, 243912M, 100 seconds
2023/04/13-21:02:50(CST) Log: region number 8 exceeds region count 8
2023/04/13-21:02:51(CST) Log: Region mask: 0xff
2023/04/13-21:03:01(CST) Log: Seconds remaining: 90
2023/04/13-21:03:11(CST) Log: Seconds remaining: 80

**Comment by nickjsanders** [comment]
On Thu, Apr 13, 2023 at 6:12 AM AlecHsiao ***@***.***> wrote:

>  is it possible to know why we have the 20 seconds before running?
>
> 2023/04/13-21:02:32(CST) Stats: Starting SAT, *243912M*, 100 seconds
>
Stressapptest fills memory with patterns before starting the test. You have
a large amount of memory
and it's likely that initializing the memory takes 20 seconds. Do you have
a full log with memory bandwidth indicated?

**Comment by AlecHsiao** [comment]
Yes, we change the log level to 20 to capture more data, I think you're correct, that is under the process to fill data in that period. Thanks for your help for that.
2023/02/22-08:00:46(CST) Starting Fill Threads 0: 30511 pages
2023/02/22-08:00:46(CST) Starting Fill Threads 1: 30511 pages
2023/02/22-08:00:46(CST) Starting Fill Threads 2: 30511 pages
2023/02/22-08:00:46(CST) Starting Fill Threads 3: 30511 pages
2023/02/22-08:00:46(CST) Starting Fill Threads 4: 30511 pages
2023/02/22-08:00:46(CST) Starting Fill Threads 5: 30511 pages
2023/02/22-08:00:46(CST) Starting Fill Threads 6: 30511 pages
2023/02/22-08:00:46(CST) Starting Fill Threads 7: 30518 pages
2023/02/22-08:00:46(CST) Log: Thread 0 running on core ID 81 mask FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF (FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF).
2023/02/22-08:00:46(CST) Log: Starting fill thread 0
2023/02/22-08:00:46(CST) Log: Thread 2 running on core ID 103 mask FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF (FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF).
2023/02/22-08:00:46(CST) Log: Starting fill thread 2
2023/02/22-08:00:46(CST) Log: Thread 1 running on core ID 0 mask FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF (FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF).
2023/02/22-08:00:46(CST) Log: Starting fill thread 1
2023/02/22-08:00:46(CST) Log: Thread 3 running on core ID 19 mask FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF (FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF).
2023/02/22-08:00:46(CST) Log: Starting fill thread 3
2023/02/22-08:00:46(CST) Log: Thread 6 running on core ID 44 mask FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF (FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF).
2023/02/22-08:00:46(CST) Log: Starting fill thread 6
2023/02/22-08:00:46(CST) Log: Thread 5 running on core ID 121 mask FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF (FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF).
2023/02/22-08:00:46(CST) Log: Starting fill thread 5
2023/02/22-08:00:46(CST) Log: Thread 4 running on core ID 116 mask FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF (FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF).
2023/02/22-08:00:46(CST) Log: Starting fill thread 4
2023/02/22-08:00:46(CST) Log: Thread 7 running on core ID 52 mask FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF (FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF).
2023/02/22-08:00:46(CST) Log: Starting fill thread 7
2023/02/22-08:01:05(CST) Log: Co
[1.0.10.log](https://github.com/stressapptest/stressapptest/files/11246065/1.0.10.log)
mpleted 0: Fill thread. Status 1, 30511 pages filled
2023/02/22-08:01:05(CST) Log: Completed 7: Fill thread. Status 1, 30518 pages filled
2023/02/22-08:01:05(CST) Log: Completed 5: Fill thread. Status 1, 30511 pages filled
2023/02/22-08:01:05(CST) Log: Completed 6: Fill thread. Status 1, 30511 pages filled
2023/02/22-08:01:05(CST) Log: Completed 3: Fill thread. Status 1, 30511 pages filled
2023/02/22-08:01:05(CST) Log: Completed 1: Fill thread. Status 1, 30511 pages filled
2023/02/22-08:01:05(CST) Log: Completed 4: Fill thread. Status 1, 30511 pages filled
2023/02/22-08:01:05(CST) Log: Completed 2: Fill thread. Status 1, 30511 pages filled

**Comment by AlecHsiao** [comment]
[1.0.10.log](https://github.com/stressapptest/stressapptest/files/11246074/1.0.10.log)

**Comment by nickjsanders** [comment]
For whatever reason, initialization uses only 8 threads, which
probably isn't appropriate on large systems such as yours.

I guess a better approach would be to scale the number of initialization
and teardown threads to the number of cores
available, similar to the default for copy threads. I'll keep it in mind as
a feature request, or you can send a PR.

If you just want it to be faster and can compile yourself, you can change
the hardcoded thread counts here:
https://github.com/stressapptest/stressapptest/blob/fd4ae17eaad7fde69e1308abbe5af3181ec6ce15/src/sat.cc#L719

**Comment by AlecHsiao** [comment]
Thanks, I think that works, now I can reduce the delay time , so I think that would be enough for me, appreciated for your help !!!
