### ISSUE TITLE
Please regenerate ./configure so it doesn't say '1.07' in the version string for '1.08'

### ISSUE THREAD

**Issue by computersforpeace** [stressapptest/stressapptest#45]
An out-of-the-box build of 1.08 gives this in the runtime messages:

2017/04/06-14:30:57(PDT) Stats: SAT revision 1.0.7_autoconf, 32 bit binary

In ./configure:

PACKAGE_VERSION='1.0.7_autoconf'

Or just don't check in the autogenerated files at all :)

http://stackoverflow.com/questions/3290908/which-files-generated-by-autotools-should-i-keep-in-version-control-repository

**Comment by nickjsanders** [comment]
updated to 1.0.9 with refreshed autogenerated files.
