### ISSUE TITLE
paddr_base

### ISSUE THREAD

**Issue by HarshBokil** [stressapptest/stressapptest#51]
Why is paddr_base is ignored? I have a 32bit ARM device that passes on custom memtester app (which opens /dev/mem and maps test mem from a predefined physical address) but fails on stressapptest - it shows several miscompares

**Comment by nickjsanders** [comment]
paddr_base was used for a Google-specific mmap interface at one point. You
can add a new implementation of OsLayer::AllocateTestMem if you have some
platform specific code you'd like to use.

memtester and stressapptest have differing test patterns and usage patterns
of memory, so it's not uncommon for one to find errors where the other
didn't.

**Comment by HarshBokil** [comment]
Thanks Nick.

I had already modified AllocateTestMem to honor paddr_base, such that it opens /dev/mem and allocates like 300M or so starting from paddr_base. However, paddr_base in my case is a carved out portion of memory from Linux that is guaranteed to be untouched by any process. what puzzles me is stressapptest with --paddr_base is successful but without --paddr_base shows several miscompares. Any hints on that?

**Comment by nickjsanders** [comment]
I'd guess that the location of the failed memory cell is outside that 300M
region. Do you have the actual failure message handy?

**Comment by HarshBokil** [comment]
Yes, the address is outside those 300M:
1970/01/02-04:40:02(UTC) Log: CrcCheckPage Falling through to slow compare, CRC mismatch 000000ffbdffff01 000000ffffffff01 0000fe4957ff0380 0000fe7fffff0380 != 000000ffffffff01 000000ffffffff01 0000fe7fffff0380 0000fe7fffff0380
1970/01/02-04:40:02(UTC) Report Error: miscompare : DIMM Unknown : 1 : 103012s
1970/01/02-04:40:02(UTC) Hardware Error: miscompare on CPU 0(0x3) at 0xb2e6f960(0x0:DIMM Unknown): read:0xffffffffbdffffff, reread:0xffffffffbdffffff expected:0xffffffffffffffff

I have paddr_base at 0x1CA00000 and the physical address shown in miscompare is 0x0.

**Comment by nickjsanders** [comment]
Does this happen on multiple devices or just one?

**Comment by HarshBokil** [comment]
2 devices

**Comment by nickjsanders** [comment]
Same bits were bad in the failed word?

I ran into an interesting issue once where a driver had a bad pointer for
interrupt status, and would overwrite data in userspace. This showed up as
memory corruption, but was actually a sw error. Basically the ISR would
update a bit in an uninitialized hwaddr which sometimes would end up in
stressapptest's memory.

**Comment by HarshBokil** [comment]
There are several others in the same log:
1970/01/01-16:51:37(UTC) Log: CrcCheckPage Falling through to slow compare, CRC mismatch 000001004201ff01 000000ffffffff01 000102ae6966ff80 0001027ffffeff80 != 000000ffffffff01 000000ffffffff01 0001027ffffeff80 0001027ffffeff80
1970/01/01-16:51:37(UTC) Report Error: miscompare : DIMM Unknown : 1 : 60507s
1970/01/01-16:51:37(UTC) Hardware Error: miscompare on CPU 0(0x3) at 0xb0629a60(0x0:DIMM Unknown): read:0x0000000042020000, reread:0x0000000042020000 expected:0x0000000000000000
1970/01/01-17:51:06(UTC) Log: CrcCheckPage Falling through to slow compare, CRC mismatch 0000010041ffff01 000000ffffffff01 000100f277ff0180 0001007fffff0180 != 000000ffffffff01 000000ffffffff01 0001007fffff0180 0001007fffff0180
1970/01/01-17:51:06(UTC) Report Error: miscompare : DIMM Unknown : 1 : 64076s
1970/01/01-17:51:06(UTC) Hardware Error: miscompare on CPU 1(0x3) at 0xb5548220(0x0:DIMM Unknown): read:0xa55a5aa5e75a5aa5, reread:0xa55a5aa5e75a5aa5 expected:0xa55a5aa5a55a5aa5
1970/01/01-19:29:36(UTC) Log: CrcWarmCopyPage Falling through to slow compare, CRC mismatch 000000fffdffff01 000000ffffffff01 0000fe7c17ff0380 0000fe7fffff0380 != 000000ffffffff01 000000ffffffff01 0000fe7fffff0380 0000fe7fffff0380
1970/01/01-19:29:36(UTC) Report Error: miscompare : DIMM Unknown : 1 : 69986s
1970/01/01-19:29:36(UTC) Hardware Error: miscompare on CPU 0(0x1) at 0xa455c060(0x0:DIMM Unknown): read:0xfffffffffdffffff, reread:0xfffffffffdffffff expected:0xffffffffffffffff
1970/01/01-22:43:09(UTC) Log: CrcCheckPage Falling through to slow compare, CRC mismatch 000001003fffff01 000000ffffffff01 000102f0fffeff80 0001027ffffeff80 != 000000ffffffff01 000000ffffffff01 0001027ffffeff80 0001027ffffeff80
1970/01/01-22:43:09(UTC) Report Error: miscompare : DIMM Unknown : 1 : 81599s
1970/01/01-22:43:09(UTC) Hardware Error: miscompare on CPU 1(0x3) at 0xa57011e0(0x0:DIMM Unknown): read:0x0000000040000000, reread:0x0000000040000000 expected:0x0000000000000000
1970/01/02-04:40:02(UTC) Log: CrcCheckPage Falling through to slow compare, CRC mismatch 000000ffbdffff01 000000ffffffff01 0000fe4957ff0380 0000fe7fffff0380 != 000000ffffffff01 000000ffffffff01 0000fe7fffff0380 0000fe7fffff0380
1970/01/02-04:40:02(UTC) Report Error: miscompare : DIMM Unknown : 1 : 103012s
1970/01/02-04:40:02(UTC) Hardware Error: miscompare on CPU 0(0x3) at 0xb2e6f960(0x0:DIMM Unknown): read:0xffffffffbdffffff, reread:0xffffffffbdffffff expected:0xffffffffffffffff
1970/01/02-06:49:06(UTC) Log: CrcCheckPage Falling through to slow compare, CRC mismatch 0000000c03fffff1 000001f3fffffe11 00000c18cffff1e8 0001f4edfffe1118 != 0000000bfffffff1 000001f3fffffe11 00000c11fffff1e8 0001f4edfffe1118
1970/01/02-06:49:06(UTC) Report Error: miscompare : DIMM Unknown : 1 : 110756s
1970/01/02-06:49:06(UTC) Hardware Error: miscompare on CPU 0(0x3) at 0xb5d54260(0x0:DIMM Unknown): read:0x0100000005000000, reread:0x0100000005000000 expected:0x0100000001000000
1970/01/02-08:09:11(UTC) Log: CrcCheckPage Falling through to slow compare, CRC mismatch 0000010001ffff01 000000ffffffff01 0001028297feff80 0001027ffffeff80 != 000000ffffffff01 000000ffffffff01 0001027ffffeff80 0001027ffffeff80
1970/01/02-08:09:11(UTC) Report Error: miscompare : DIMM Unknown : 1 : 115561s
1970/01/02-08:09:11(UTC) Hardware Error: miscompare on CPU 0(0x3) at 0xa59045a0(0x0:DIMM Unknown): read:0x0000000002000000, reread:0x0000000002000000 expected:0x0000000000000000
1970/01/02-08:28:19(UTC) Log: CrcCheckPage Falling through to slow compare, CRC mismatch 0000010001ffff01 000000ffffffff01 0001028387feff80 0001027ffffeff80 != 000000ffffffff01 000000ffffffff01 0001027ffffeff80 0001027ffffeff80
1970/01/02-08:28:19(UTC) Report Error: miscompare : DIMM Unknown : 1 : 116709s
1970/01/02-08:28:19(UTC) Hardware Error: miscompare on CPU 1(0x3) at 0xad63c1e0(0x0:DIMM Unknown): read:0x0000000002000000, reread:0x0000000002000000 expected:0x0000000000000000
1970/01/02-11:54:14(UTC) Log: CrcCheckPage Falling through to slow compare, CRC mismatch 000001004601ff01 000000ffffffff01 0001027ef8a6ffa0 00010267fffeffa0 != 000000ffffffff01 000000ffffffff01 00010267fffeffa0 00010267fffeffa0
1970/01/02-11:54:14(UTC) Report Error: miscompare : DIMM Unknown : 1 : 129064s
1970/01/02-11:54:14(UTC) Hardware Error: miscompare on CPU 0(0x3) at 0xa9c69d60(0x0:DIMM Unknown): read:0x0000020046020200, reread:0x0000020046020200 expected:0x0000020000000200
1970/01/02-15:12:01(UTC) Log: CrcCheckPage Falling through to slow compare, CRC mismatch 0000010001ffff01 000000ffffffff01 0001028337feff80 0001027ffffeff80 != 000000ffffffff01 000000ffffffff01 0001027ffffeff80 0001027ffffeff80
1970/01/02-15:12:01(UTC) Report Error: miscompare : DIMM Unknown : 1 : 140931s
1970/01/02-15:12:01(UTC) Hardware Error: miscompare on CPU 0(0x3) at 0xa5160320(0x0:DIMM Unknown): read:0x0000000002000000, reread:0x0000000002000000 expected:0x0000000000000000
1970/01/01-16:51:37(UTC) Log: CrcCheckPage Falling through to slow compare, CRC mismatch 000001004201ff01 000000ffffffff01 000102ae6966ff80 0001027ffffeff80 != 000000ffffffff01 000000ffffffff01 0001027ffffeff80 0001027ffffeff80
1970/01/01-16:51:37(UTC) Report Error: miscompare : DIMM Unknown : 1 : 60507s
1970/01/01-16:51:37(UTC) Hardware Error: miscompare on CPU 0(0x3) at 0xb0629a60(0x0:DIMM Unknown): read:0x0000000042020000, reread:0x0000000042020000 expected:0x0000000000000000

**Comment by nickjsanders** [comment]
Not sure. Could be a driver problem corrupting memory, or could be a design
problem with your board. Stressapptest really is just writing the data and
reading it back again, and noticing that some of the bits are no longer the
same. So there's not really much likelihood that it's a bug in
stressapptest.

**Comment by nickjsanders** [comment]
Maybe try lowering the memory clock and see if the errors go away?

**Comment by manojngb** [comment]
Hi Nick,
     In your comment about the bad pointer in the driver, rises a question: At low level, is there a pause (some other process is going to be run) between write and read and reread at a particular address. or at DDR phy level, is it read after write command (consecutive / non-preemptive) ?

**Comment by nickjsanders** [comment]
stressapptest writes the data, then comes back to read it after some time.
So at any given time something like 60% of memory is written and waiting to
be read back. This means any bad kernel pointer dereferences are likely to
cause stressapptest errors.

When a miscompare is detected, stressapptest will flush the cache and
reread the same DRAM location, and print out "expected X, read Y, reread Z"
with the intention that if reread is the same as read, likely the data was
written incorrectly or corrupted in DRAM. if reread is the same as
expected, the DDR read transaction had some problem but the data in DRAM is
actually not corrupted.

**Comment by HarshBokil** [comment]
Closing
