### ISSUE TITLE
The Stressapptest won't keep running any more after the first 600sec 

### ISSUE THREAD

**Issue by kyewonh** [stressapptest/stressapptest#52]
it looks working before 600sec of test time but  it just stops  after 600sec.

Linux optane 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Log: Commandline - stressapptest -m 56 -i 56 --local_numa -l test4.log -s 3600 -M 667133 --pause_duration 60

Stats: SAT revision 1.0.6_autoconf, 64 bit binary
Log: buildd @ kapok on Wed Jan 21 17:09:35 UTC 2015 from open source release
Log: 1 nodes, 112 cpus.
Log: Prefer plain malloc memory allocation.
Log: Using memaligned allocation at 0x7f0169b63000.
Stats: Starting SAT, 667133M, 3600 seconds
Log: region number 1 exceeds region count 1
Log: Region mask: 0x1
Log: Seconds remaining: 3590
Log: Seconds remaining: 3580
Log: Seconds remaining: 3570
Log: Seconds remaining: 3560
Log: Seconds remaining: 3550
Log: Seconds remaining: 3540
Log: Seconds remaining: 3530
Log: Seconds remaining: 3520
Log: Seconds remaining: 3510
Log: Seconds remaining: 3500
Log: Seconds remaining: 3490
Log: Seconds remaining: 3480
Log: Seconds remaining: 3470
Log: Seconds remaining: 3460
Log: Seconds remaining: 3450
Log: Seconds remaining: 3440
Log: Seconds remaining: 3430
Log: Seconds remaining: 3420
Log: Seconds remaining: 3410
Log: Seconds remaining: 3400
Log: Seconds remaining: 3390
Log: Seconds remaining: 3380
Log: Seconds remaining: 3370
Log: Seconds remaining: 3360
Log: Seconds remaining: 3350
Log: Seconds remaining: 3340
Log: Seconds remaining: 3330
Log: Seconds remaining: 3320
Log: Seconds remaining: 3310
Log: Seconds remaining: 3299
Log: Seconds remaining: 3290
Log: Seconds remaining: 3280
Log: Seconds remaining: 3270
Log: Seconds remaining: 3260
Log: Seconds remaining: 3250
Log: Seconds remaining: 3240
Log: Seconds remaining: 3230
Log: Seconds remaining: 3220
Log: Seconds remaining: 3210
Log: Seconds remaining: 3200
Log: Seconds remaining: 3190
Log: Seconds remaining: 3180
Log: Seconds remaining: 3170
Log: Seconds remaining: 3160
Log: Seconds remaining: 3150
Log: Seconds remaining: 3140
Log: Seconds remaining: 3130
Log: Seconds remaining: 3120
Log: Seconds remaining: 3110
Log: Seconds remaining: 3100
Log: Seconds remaining: 3090
Log: Seconds remaining: 3080
Log: Seconds remaining: 3070
Log: Seconds remaining: 3060
Log: Seconds remaining: 3050
Log: Seconds remaining: 3040
Log: Seconds remaining: 3030
Log: Seconds remaining: 3020
Log: Seconds remaining: 3010
Log: Seconds remaining: 3000
Log: Pausing worker threads in preparation for power spike (3000 seconds remaining)
Log: Seconds remaining: 2990
Log: Seconds remaining: 2980
Log: Seconds remaining: 2970
Log: Seconds remaining: 2960
Log: Seconds remaining: 2950
Log: Seconds remaining: 2940
Log: Resuming worker threads to cause a power spike (2940 seconds remaining)
--> No more progress.

test time 600sec
Log: Commandline - stressapptest -s 600 -l test_normal2.log
Stats: SAT revision 1.0.6_autoconf, 64 bit binary
Log: buildd @ kapok on Wed Jan 21 17:09:35 UTC 2015 from open source release
Log: 1 nodes, 112 cpus.
Log: Defaulting to 112 copy threads
Log: Total 192076 MB. Free 190754 MB. Hugepages 0 MB. Targeting 182281 MB (94%)
Log: Prefer plain malloc memory allocation.
Log: Using memaligned allocation at 0x7f23da35c000.
Stats: Starting SAT, 182281M, 600 seconds
Log: Region mask: 0x1
Log: Seconds remaining: 590
Log: Seconds remaining: 580
Log: Seconds remaining: 570
Log: Seconds remaining: 560
Log: Seconds remaining: 550
Log: Seconds remaining: 540
Log: Seconds remaining: 530
Log: Seconds remaining: 520
Log: Seconds remaining: 510
Log: Seconds remaining: 500
Log: Seconds remaining: 490
Log: Seconds remaining: 480
Log: Seconds remaining: 470
Log: Seconds remaining: 460
Log: Seconds remaining: 450
Log: Seconds remaining: 440
Log: Seconds remaining: 430
Log: Seconds remaining: 420
Log: Seconds remaining: 410
Log: Seconds remaining: 400
Log: Seconds remaining: 390
Log: Seconds remaining: 380
Log: Seconds remaining: 370
Log: Seconds remaining: 360
Log: Seconds remaining: 350
Log: Seconds remaining: 340
Log: Seconds remaining: 330
Log: Seconds remaining: 320
Log: Seconds remaining: 310
Log: Seconds remaining: 300
Log: Seconds remaining: 290
Log: Seconds remaining: 280
Log: Seconds remaining: 270
Log: Seconds remaining: 260
Log: Seconds remaining: 250
Log: Seconds remaining: 240
Log: Seconds remaining: 230
Log: Seconds remaining: 220
Log: Seconds remaining: 210
Log: Seconds remaining: 200
Log: Seconds remaining: 190
Log: Seconds remaining: 180
Log: Seconds remaining: 170
Log: Seconds remaining: 160
Log: Seconds remaining: 150
Log: Seconds remaining: 140
Log: Seconds remaining: 130
Log: Seconds remaining: 120
Log: Seconds remaining: 110
Log: Seconds remaining: 100
Log: Seconds remaining: 90
Log: Seconds remaining: 80
Log: Seconds remaining: 70
Log: Seconds remaining: 60
Log: Seconds remaining: 50
Log: Seconds remaining: 40
Log: Seconds remaining: 30
Log: Seconds remaining: 20
Log: Seconds remaining: 10
Stats: Found 0 hardware incidents
Stats: Completed: 47925528.00M in 600.08s 79864.79MB/s, with 0 hardware incidents, 0 errors
Stats: Memory Copy: 47925528.00M at 79873.41MB/s
Stats: File Copy: 0.00M at 0.00MB/s
Stats: Net Copy: 0.00M at 0.00MB/s
Stats: Data Check: 0.00M at 0.00MB/s
Stats: Invert Data: 0.00M at 0.00MB/s
Stats: Disk: 0.00M at 0.00MB/s

Status: PASS - please verify no corrected errors

**Comment by nickjsanders** [comment]
Log: Seconds remaining: 2940
Log: Resuming worker threads to cause a power spike (2940 seconds remaining)
--> No more progress.
This is likely one of two problems:

1) the last line here indicates that stressapptest ran a load step (ramped
112 cores from idle to 100% simultaneously). So it may be that the system
encountered a power related error. Did the system stop responding, or did
stressapptest app stop responding? If the system stopped responding, this
is probably the issue.

2) The "power spike" feature uses pthread barriers, which have had api
changes over the years. So it may be a bug that this combination of
OS/libpthread/stressapptest just doesn't work properly, and the app is
stuck incorrectly waiting on a mutex. Can you run stressapptest with
"-m 8 --pause_duration
5 --pause_delay 20 -s 300"? This will run through the pthreads code without
causing much load on your system. If the app gets stuck but the system is
still running OK otherwise, this is likely the issue.

**Comment by kyewonh** [comment]
1. stressapptest is working well on Redhat 6.8 without stop.  I think stfressapptest app stops responding because the system is still running on Linux.
  --> I attached the stressapptest result on Redhat OS

2. this is the output result .
Log: Commandline - stressapptest -m 8 -l test5.log -s 300 -M 667133 --pause_duration 5 --pause_delay 20
Stats: SAT revision 1.0.6_autoconf, 64 bit binary
Log: buildd @ kapok on Wed Jan 21 17:09:35 UTC 2015 from open source release
Log: 1 nodes, 112 cpus.
Log: Prefer plain malloc memory allocation.
Log: Using memaligned allocation at 0x7e8613ef7000.
Stats: Starting SAT, 667133M, 300 seconds
Log: region number 1 exceeds region count 1
Log: Region mask: 0x1
Log: Seconds remaining: 290
Log: Seconds remaining: 280
Log: Pausing worker threads in preparation for power spike (280 seconds remaining)
Log: Resuming worker threads to cause a power spike (275 seconds remaining)
Log: Seconds remaining: 270
Log: Seconds remaining: 260
Log: Pausing worker threads in preparation for power spike (260 seconds remaining)
Log: Resuming worker threads to cause a power spike (255 seconds remaining)
Log: Seconds remaining: 250
Log: Seconds remaining: 240
Log: Pausing worker threads in preparation for power spike (240 seconds remaining)
Log: Resuming worker threads to cause a power spike (235 seconds remaining)
Log: Seconds remaining: 230
Log: Seconds remaining: 220
Log: Pausing worker threads in preparation for power spike (220 seconds remaining)
Log: Resuming worker threads to cause a power spike (215 seconds remaining)
Log: Seconds remaining: 210
Log: Seconds remaining: 200
Log: Pausing worker threads in preparation for power spike (200 seconds remaining)
Log: Resuming worker threads to cause a power spike (195 seconds remaining)
Log: Seconds remaining: 190
Log: Seconds remaining: 180
Log: Pausing worker threads in preparation for power spike (180 seconds remaining)
Log: Resuming worker threads to cause a power spike (175 seconds remaining)
Log: Seconds remaining: 170
Log: Seconds remaining: 160
Log: Pausing worker threads in preparation for power spike (160 seconds remaining)
Log: Resuming worker threads to cause a power spike (155 seconds remaining)
Log: Seconds remaining: 150
Log: Seconds remaining: 140
Log: Pausing worker threads in preparation for power spike (140 seconds remaining)
Log: Resuming worker threads to cause a power spike (135 seconds remaining)
Log: Seconds remaining: 130
Log: Seconds remaining: 120
Log: Pausing worker threads in preparation for power spike (120 seconds remaining)
Log: Resuming worker threads to cause a power spike (115 seconds remaining)
Log: Seconds remaining: 110
Log: Seconds remaining: 100
Log: Pausing worker threads in preparation for power spike (100 seconds remaining)
Log: Resuming worker threads to cause a power spike (95 seconds remaining)
Log: Seconds remaining: 90
Log: Seconds remaining: 80
Log: Pausing worker threads in preparation for power spike (80 seconds remaining)
Log: Resuming worker threads to cause a power spike (75 seconds remaining)
Log: Seconds remaining: 70
Log: Seconds remaining: 60
Log: Pausing worker threads in preparation for power spike (60 seconds remaining)
Log: Resuming worker threads to cause a power spike (55 seconds remaining)
Log: Seconds remaining: 50
Log: Seconds remaining: 40
Log: Pausing worker threads in preparation for power spike (40 seconds remaining)
Log: Resuming worker threads to cause a power spike (35 seconds remaining)
Log: Seconds remaining: 30
Log: Seconds remaining: 20
Log: Pausing worker threads in preparation for power spike (20 seconds remaining)
Log: Resuming worker threads to cause a power spike (15 seconds remaining)
Log: Seconds remaining: 10
Stats: Found 0 hardware incidents
Stats: Completed: 716558.00M in 300.91s 2381.31MB/s, with 0 hardware incidents, 0 errors
Stats: Memory Copy: 716558.00M at 2385.93MB/s
Stats: File Copy: 0.00M at 0.00MB/s
Stats: Net Copy: 0.00M at 0.00MB/s
Stats: Data Check: 0.00M at 0.00MB/s
Stats: Invert Data: 0.00M at 0.00MB/s
Stats: Disk: 0.00M at 0.00MB/s

Status: PASS - please verify no corrected errors

[sat.log](https://github.com/stressapptest/stressapptest/files/1422690/sat.log)

**Comment by kyewonh** [comment]
this looks like  only Ubuntu16.04 issue.
Centos 7 has no this problem. Now  i will move to Centos 7 to test system with stresssapptest.
