### ISSUE TITLE
stressapptest CRC mismatch, Hardware Error: miscompare on CPU

### ISSUE THREAD

**Issue by SS203** [stressapptest/stressapptest#56]
Hi
I got the test PASS(Status: PASS - please verify no corrected errors) of stressapptest result, but there are some "CRC mismatch", "Hardware Error: miscompare" events occurred. Does the events mean my system has bad DIMM or bad CPU problem? If so, why the status shows PASS?  Could anyone help me to check on my question? Thanks.

**Comment by nickjsanders** [comment]
Yep, that's a bug
<https://github.com/stressapptest/stressapptest/blob/880fb47e66e138b49f059fa6f5739a2bef8a84a3/src/worker.cc#L1243>.
Thanks for reporting!

I'm not sure what kind of hardware failure you are having, the CRC failed
but the correct data all passed though successfully. So possibly a CPU
error? I haven't encountered this before.

**Comment by SS203** [comment]
Thanks Nick.

2017-12-05 8:11 GMT+08:00 nickjsanders <notifications@github.com>:

> Yep, that's a bug
> <https://github.com/stressapptest/stressapptest/blob/
> 880fb47e66e138b49f059fa6f5739a2bef8a84a3/src/worker.cc#L1243>.
> Thanks for reporting!
>
> I'm not sure what kind of hardware failure you are having, the CRC failed
> but the correct data all passed though successfully. So possibly a CPU
> error? I haven't encountered this before.
>

**Comment by nickjsanders** [comment]
Fixed.
