### ISSUE TITLE
What's the purpose of cpu frequency test thread please?

### ISSUE THREAD

**Issue by shanshanzhang90** [stressapptest/stressapptest#68]
Hi,

what's the purpose of cpu frequency test thread please? Is it only used to detect current CPU frequency? And report error if the frequency is lower than the threshold?
I have checked the cpu frequency and ddr frequency, they are always at there maximum value, is this expected?

**Comment by tommybreak** [comment]
压力测试，当然是测试硬件的最大潜能

**Comment by nickjsanders** [comment]
As above, it's expected that cpu frequency will generally be the max frequency during a stress test, until thermal throttling. The test exists to check that the reported frequency is the actual frequency, as occasionally crystals or PLLs can be defective, or the clocking mechanism in sw works unexpectedly..
