### ISSUE TITLE
DDR stress test failed

### ISSUE THREAD

**Issue by jekenpwn** [stressapptest/stressapptest#71]
Hi
I met a issue, when I stress test my DDR via stresstestapp, it was show below error, Could you tell me some idea about what is wrong for my DDR?
Hardware issue or Software issue ? 
------------------------------------------------------------
2019/09/24-17:39:39(UTC) Log: CrcCopyPage CRC mismatch 000000ff7fffff01 000000ff7fffff01 000101eebffeffa0 000101eebffeffa0 != 000000ffffffff01 000000ffffffff01 00010267fffeffa0 00010267fffeffa0, but no miscompares found. Retrying with fresh data.
2019/09/24-17:39:39(UTC) Report Error: miscompare : DIMM Unknown : 1 : 882s
2019/09/24-17:39:39(UTC) Hardware Error: miscompare on CPU 1(0x2) at 0xffff83bf0860(0x711f0863:DIMM Unknown): read:0x0000000000000000, reread:0x0000000000000000 expected:0x2000000020000000
2019/09/24-17:39:39(UTC) Report Error: miscompare : DIMM Unknown : 1 : 882s
2019/09/24-17:39:39(UTC) Hardware Error: miscompare on CPU 1(0x2) at 0xffff83bf0868(0x711f086b:DIMM Unknown): read:0x0000000000000000, reread:0x0000000000000000 expected:0x2000000020000000
2019/09/24-17:39:39(UTC) Report Error: miscompare : DIMM Unknown : 1 : 882s
2019/09/24-17:39:39(UTC) Hardware Error: miscompare on CPU 1(0x2) at 0xffff83bf0870(0x711f0873:DIMM Unknown): read:0x0000000000000000, reread:0x0000000000000000 expected:0x2000000020000000
2019/09/24-17:39:39(UTC) Report Error: miscompare : DIMM Unknown : 1 : 882s
2019/09/24-17:39:39(UTC) Hardware Error: miscompare on CPU 1(0x2) at 0xffff83bf0878(0x711f087b:DIMM Unknown): read:0x0000000000000000, reread:0x0000000000000000 expected:0x2000000020000000
2019/09/24-17:39:47(UTC) Log: Seconds remaining: 910
2019/09/24-17:39:57(UTC) Log: Seconds remaining: 900
2019/09/24-17:40:07(UTC) Log: Seconds remaining: 890
----------------------------------------------------------------------------------------------

BR,

**Comment by nickjsanders** [comment]
This is probably a hardware issue. The software wrote 0x2000000020000000 to memory, and read back 0x0000000000000000.
