### ISSUE TITLE
Fails to find ram fault when Drac says memory fault on one stick.

### ISSUE THREAD

**Issue by stheno** [stressapptest/stressapptest#78]
I have a problematic stick of ram on my Dell r900 with 80gb ram.
The Drac reports this stick as having an issue but this program says all ram passed.

Ubuntu 20.04.1

**Comment by vhulagov** [comment]
stressapptest is the utility to produce load on memory subsystem and to check data integrity among transactions, not to check MCA banks and do PFA (Predictive failure analysis) stuff like DRAC do.
Please, trust DRAC or use mcelog in daemon mode with stressapptest load in parallel.

**Comment by nickjsanders** [comment]
As vhulagov says, stressapptest provides load and checks for data corruption. You'd need to check for ECC errors separately.
