### ISSUE TITLE
/src/sattypes.h: kCacheLineSize?

### ISSUE THREAD

**Issue by sagiocean** [stressapptest/stressapptest#89]
I'm newbie to compute...

https://github.com/stressapptest/stressapptest/blob/master/src/sattypes.h

static const int kCacheLineSize = 64;

above constant has been defined, is cache line size is 64 byte or 64 bit?

**Comment by sagiocean** [comment]
i'm assuming 64byte

**Comment by nickjsanders** [comment]
Yes, 64 byte. It's not a runtime argument but you could recompile if you
have a system with different cache line size.
