### ISSUE TITLE
Processor Stress Test - Hitting Max TDP

### ISSUE THREAD

**Issue by jyasir** [stressapptest/stressapptest#90]
Is the processor stress test expected to draw processor that meets max TDP spec and what are the default parameters to run the the processor in max torture mode?

**Comment by nickjsanders** [comment]
The standard arguments should be pretty good for approaching max TDP. These are probably the most warm: 
`stressapptest -s [seconds]`  // run a thread on each core
`stressapptest -W -s [seconds]` // run a vectorized thread on each core

Note that stressapptest doesn't touch GPU, TPU, or other accelerators, so you would want to load them separately.
